import type { Place, SafetyReport, WeatherData } from '@/types';

export const NAGPUR_CENTER: [number, number] = [21.1458, 79.0882];
export const NAGPUR_ZOOM = 13;

// Wikimedia Commons images use Special:FilePath which serves the actual file directly.
// All Wikimedia photos are CC-BY-SA or public domain from Wikimedia Commons contributors.
// For places without a specific Wikimedia photo, a clearly-labelled representative
// image from Pexels (license-free) is used instead — never claimed to be a real photo
// of the specific location.

const WM = (filename: string, width = 940) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${filename}?width=${width}`;

export const PLACES: Place[] = [
  // ────────────── HERITAGE & LANDMARKS ──────────────
  {
    id: 'deekshabhoomi',
    name: 'Deekshabhoomi',
    category: 'heritage',
    description: 'A sacred Buddhist monument and pilgrimage site where Dr. B.R. Ambedkar converted to Buddhism with approximately 380,000 followers in 1956. The stupa is an architectural marvel and one of the most significant Buddhist sites in India.',
    lat: 21.1562, lng: 79.0726,
    address: 'South Ambazari Road, Nagpur',
    area: 'Sadar',
    images: [
      WM('Deekshabhoomi,_Nagpur_in_India.jpg'),
      WM('Deekshabhumi_Nagpur.jpg'),
      WM('Deekshabhoomi_-_panoramio.jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — CC-BY-SA contributors',
    source: 'OpenStreetMap / Wikipedia',
    sourceUrl: 'https://en.wikipedia.org/wiki/Deekshabhoomi',
    lastUpdated: '2025-03-15',
    hours: 'Open daily, 6:00 AM – 8:00 PM',
    entryFee: 'Free entry',
    verified: true,
    tags: ['Buddhist', 'Pilgrimage', 'Historical', 'Stupa'],
    historicalContext: 'On October 14, 1956, Dr. B.R. Ambedkar embraced Buddhism here along with nearly 380,000 followers, making it the largest religious conversion in history. The stupa was completed in 2001.',
    established: '1956 (site), 2001 (stupa)',
    nearbyIds: ['ambazari-lake', 'sitabuldi-fort', 'futala-lake'],
  },
  {
    id: 'ambazari-lake',
    name: 'Ambazari Lake & Garden',
    category: 'park',
    description: 'One of Nagpur\'s largest and most scenic lakes, surrounded by a well-maintained garden. A popular spot for boating, evening walks, and family outings with a musical fountain show. The Nag River originates from this lake.',
    lat: 21.1389, lng: 79.0497,
    address: 'Ambazari Lake Road, Nagpur',
    area: 'Ambazari',
    images: [
      WM('Ambazari_lake_nagpur.jpg'),
      WM('Ambazari_Lake_(3128290896).jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — CC-BY-SA contributors (Wiki Loves Earth)',
    source: 'OpenStreetMap / NMC',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ambazari_Lake',
    lastUpdated: '2025-02-20',
    hours: '9:00 AM – 7:00 PM (Tue–Sun), closed Monday',
    entryFee: '₹10 adults, ₹5 children',
    verified: true,
    tags: ['Lake', 'Garden', 'Boating', 'Fountain', 'Family'],
    nearbyIds: ['deekshabhoomi'],
  },
  {
    id: 'sitabuldi-fort',
    name: 'Sitabuldi Fort',
    category: 'landmark',
    description: 'A historic hilltop fort built by the Bhonsle dynasty in the 18th century, overlooking the city. The fort houses a memorial for soldiers who died in the 1857 war of independence.',
    lat: 21.1458, lng: 79.0882,
    address: 'Sitabuldi, Nagpur',
    area: 'Sitabuldi',
    images: [
      WM('Sitabuldi_fort_gate.JPG'),
      WM('Night_at_Sitabuldi_Nagpur.jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — Gppande, CC-BY-SA',
    source: 'OpenStreetMap / ASI',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sitabuldi_Fort',
    lastUpdated: '2025-01-10',
    hours: 'Open on public holidays only',
    entryFee: 'Free',
    verified: true,
    tags: ['Fort', 'Historical', 'Hilltop', 'Military'],
    historicalContext: 'Built by the Bhonsle rulers of Nagpur, the fort was the site of the Battle of Sitabuldi in 1817 between the Marathas and the British East India Company.',
    established: 'Late 18th century',
    nearbyIds: ['zero-mile', 'deekshabhoomi', 'kasturchand-park'],
  },
  {
    id: 'zero-mile',
    name: 'Zero Mile Stone',
    category: 'landmark',
    description: 'The geographical center point of India, erected by the British during the Great Trigonometrical Survey in 1907. A sandstone pillar marking the zero milestone from which all distances in India were historically measured.',
    lat: 21.1499, lng: 79.0806,
    address: 'Zero Mile, Nagpur Station Road',
    area: 'Sitabuldi',
    images: [
      WM('Zero_Mile_Stone,_Nagpur,_Maharashtra.jpg'),
      WM('Zero_mile_nagpur.jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — CC-BY-SA (Wiki Loves Monuments)',
    source: 'OpenStreetMap / ASI',
    sourceUrl: 'https://en.wikipedia.org/wiki/Zero_Mile_Stone_(Nagpur)',
    lastUpdated: '2025-01-10',
    verified: true,
    tags: ['Monument', 'Geographic Center', 'Colonial', 'Survey'],
    historicalContext: 'Erected during the Great Trigonometrical Survey of India in 1907, this milestone was considered the geographic center of India. The pillar stands 310.948 m above mean sea level.',
    established: '1907',
    nearbyIds: ['sitabuldi-fort', 'nagpur-central-museum'],
  },
  {
    id: 'ramtek-temple',
    name: 'Ramtek Temple',
    category: 'heritage',
    description: 'An ancient Hindu temple complex atop a hill, believed to be where Lord Rama rested during exile. The site includes the Kalidas Memorial, honoring the great Sanskrit poet. Temples have existed here since at least the 5th century Vakataka period.',
    lat: 21.2717, lng: 79.2625,
    address: 'Ramtek, 50km from Nagpur',
    area: 'Ramtek',
    images: [
      WM('Ram_temple_Ramtek_Nagpur.jpeg'),
      WM('Shri_Ram_temple_and_fort_temples_of_Ramtek_01.jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — CC-BY-SA contributors',
    source: 'OpenStreetMap / ASI',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ramtek',
    lastUpdated: '2025-03-01',
    hours: '5:00 AM – 9:00 PM daily',
    verified: true,
    tags: ['Temple', 'Hill', 'Ramayana', 'Kalidas', 'Ancient', 'Vakataka'],
    historicalContext: 'Legend says Lord Rama rested here during his exile. The site has been a religious sanctuary since the Vakataka dynasty (5th century). The Kalidas Memorial commemorates poet Kalidas, who is believed to have written Meghaduta here.',
    established: '5th century (site), current structure ~14th century',
    nearbyIds: ['khindsi-lake'],
  },
  {
    id: 'khindsi-lake',
    name: 'Khindsi Lake',
    category: 'park',
    description: 'A large natural lake near Ramtek offering water sports, boating, and a nearby water park. One of the largest lakes in the region surrounded by forested hills.',
    lat: 21.2833, lng: 79.2317,
    address: 'Near Ramtek, Nagpur district',
    area: 'Ramtek',
    images: [
      'https://images.pexels.com/photos/8987704/pexels-photo-8987704.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (no specific Wikimedia photo available)',
    source: 'OpenStreetMap / Tourism Board',
    lastUpdated: '2025-02-28',
    hours: '8:00 AM – 6:00 PM',
    entryFee: '₹30 entry, boating extra',
    verified: true,
    tags: ['Lake', 'Water Sports', 'Boating', 'Forest'],
    nearbyIds: ['ramtek-temple'],
  },
  {
    id: 'maharajbagh',
    name: 'Maharajbagh Zoo & Garden',
    category: 'park',
    description: 'A historic botanical garden and small zoo established by the Bhonsle royal family. Home to a variety of animals, birds, and beautifully maintained gardens.',
    lat: 21.1394, lng: 79.0656,
    address: 'Maharajbagh Road, Nagpur',
    area: 'Civil Lines',
    images: [
      WM('A_view_of_Maharajbag,_Nagpur.jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — Ganesh Dhamodkar, CC-BY-SA',
    source: 'OpenStreetMap / PDKV',
    sourceUrl: 'https://en.wikipedia.org/wiki/Maharajbagh_Zoo',
    lastUpdated: '2025-01-28',
    hours: '9:00 AM – 5:00 PM (closed Monday)',
    entryFee: '₹20 adults, ₹10 children',
    verified: true,
    tags: ['Zoo', 'Garden', 'Botanical', 'Family', 'Royal'],
    historicalContext: 'Established by the Bhonsle royal family of Nagpur, this garden was part of the royal estate. It is now maintained by the Panjabrao Deshmukh Krishi Vidyapeeth.',
    nearbyIds: ['deekshabhoomi', 'ravi-bhavan', 'nagpur-central-museum'],
  },
  {
    id: 'nagpur-central-museum',
    name: 'Central Museum (Nagpur)',
    category: 'cultural',
    description: 'Established in 1863, the Central Museum houses important collections of archaeology, art, and natural history from the Vidarbha region, including rare inscriptions, sculptures, and dinosaur fossils.',
    lat: 21.1494, lng: 79.0822,
    address: 'Civil Lines, Nagpur',
    area: 'Civil Lines',
    images: [
      WM('Central_Museum_Nagpur.jpg'),
      WM('Nagpur_Central_Museum,_Painting_Gallery,_Oct_2019.jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — CC-BY-SA contributors',
    source: 'OpenStreetMap / ASI',
    sourceUrl: 'https://en.wikipedia.org/wiki/Nagpur_Central_Museum',
    lastUpdated: '2025-01-15',
    hours: '10:00 AM – 5:00 PM (closed Monday)',
    entryFee: '₹10',
    verified: true,
    tags: ['Museum', 'Archaeology', 'Art', 'History', 'Inscriptions', 'Fossils'],
    historicalContext: 'Founded in 1863 during British rule, it is one of the oldest museums in India. Its collection includes artifacts from the Vidarbha region spanning centuries, including dinosaur fossils and rare coins.',
    established: '1863',
    nearbyIds: ['zero-mile', 'sitabuldi-fort', 'maharajbagh'],
  },
  {
    id: 'koradi-temple',
    name: 'Koradi Devi Temple',
    category: 'heritage',
    description: 'A revered ancient temple dedicated to Goddess Koradi Devi, located by a lake. One of the Shakti Peethas and a major pilgrimage site during Navratri.',
    lat: 21.2611, lng: 79.1167,
    address: 'Koradi, 15km from Nagpur',
    area: 'Koradi',
    images: [
      'https://images.pexels.com/photos/8123962/pexels-photo-8123962.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (Indian temple, no specific Wikimedia photo of Koradi Devi available)',
    source: 'OpenStreetMap / Temple Trust',
    sourceUrl: 'https://en.wikipedia.org/wiki/Koradi',
    lastUpdated: '2025-02-22',
    hours: '5:00 AM – 9:00 PM daily',
    verified: true,
    tags: ['Temple', 'Shakti Peetha', 'Pilgrimage', 'Navratri'],
    historicalContext: 'An ancient temple considered one of the Shakti Peethas. During Navratri, over 50,000 devotees visit for the Koradi Devi yatra.',
    nearbyIds: ['deekshabhoomi'],
  },
  {
    id: 'futala-lake',
    name: 'Futala Lake',
    category: 'attraction',
    description: 'A historic lake covering 60 acres, built by the Bhosle kings of Nagpur. Now a popular evening destination with food stalls and a promenade, known for its sunset views and local street food.',
    lat: 21.1206, lng: 79.0567,
    address: 'Futala Lake Road, Nagpur',
    area: 'Sadar',
    images: [
      WM('Futala_Lake,_Nagpur.jpg'),
      WM('Futala_Lake,_Nagpur_2.jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — CC-BY-SA (Wiki Loves Earth 2017)',
    source: 'OpenStreetMap / NMC',
    sourceUrl: 'https://en.wikipedia.org/wiki/Futala_Lake',
    lastUpdated: '2025-03-08',
    hours: 'Open 24 hours, food stalls from 5 PM',
    verified: true,
    tags: ['Lake', 'Sunset', 'Street Food', 'Evening', 'Historic', 'Bhosle'],
    historicalContext: 'Built by the Bhosle kings of Nagpur, the lake covers 60 acres (24 ha). It has been a gathering place for generations of Nagpur residents.',
    nearbyIds: ['deekshabhoomi', 'saoji-street', 'telankhedi-garden'],
  },

  // ────────────── NEW HERITAGE & CULTURAL ──────────────
  {
    id: 'raman-science-centre',
    name: 'Raman Science Centre & Planetarium',
    category: 'cultural',
    description: 'An interactive science museum and planetarium named after Nobel laureate Sir C.V. Raman. Features hands-on exhibits, a 3D theatre, and planetarium shows — a great destination for families and science enthusiasts.',
    lat: 21.1217, lng: 79.0600,
    address: 'Opposite Gandhi Sagar Lake, Nagpur',
    area: 'Sadar',
    images: [
      WM('Raman_Science_Centre_Nagpur.jpg'),
      WM('Raman_Science_Centre_and_Planetarium.jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — CC-BY-SA 4.0',
    source: 'OpenStreetMap / NCSM',
    sourceUrl: 'https://en.wikipedia.org/wiki/Raman_Science_Centre',
    lastUpdated: '2025-03-12',
    hours: '10:30 AM – 7:00 PM (closed Monday)',
    entryFee: '₹60 adults, ₹40 children (planetarium extra)',
    verified: true,
    tags: ['Science', 'Museum', 'Planetarium', 'Family', 'Educational'],
    historicalContext: 'Established in 1992 by the National Council of Science Museums, it is named after Sir C.V. Raman, India\'s first Nobel laureate in science.',
    established: '1992',
    nearbyIds: ['gandhi-sagar', 'futala-lake'],
  },
  {
    id: 'narrow-gauge-rail-museum',
    name: 'Narrow Gauge Rail Museum',
    category: 'cultural',
    description: 'A unique museum dedicated to the narrow-gauge railways that once connected the Vidarbha region. Features vintage locomotives, coaches, and railway artifacts, including a working steam engine display.',
    lat: 21.1483, lng: 79.0789,
    address: 'Kingsway, S E Old Railway Feeder Road, Nagpur',
    area: 'Civil Lines',
    images: [
      WM('Museum,_Narrow_Gauge_Rail_Museum._Nagpur_-_panoramio.jpg'),
      WM('Water_Fountain_at_Narrow_Gauge_Rail_Museum_-_panoramio.jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — Kailash Mohankar, CC-BY-SA',
    source: 'OpenStreetMap / Indian Railways',
    sourceUrl: 'https://en.wikipedia.org/wiki/Narrow_Gauge_Rail_Museum,_Nagpur',
    lastUpdated: '2025-02-18',
    hours: '9:00 AM – 5:00 PM (closed Monday)',
    entryFee: '₹20',
    verified: true,
    tags: ['Railway', 'Museum', 'Heritage', 'Locomotives', 'Steam'],
    historicalContext: 'The museum preserves the legacy of the narrow-gauge rail network that served the Vidarbha and Central Provinces regions from the early 1900s until gauge conversion in the 2010s.',
    established: '2008',
    nearbyIds: ['zero-mile', 'sitabuldi-fort'],
  },

  // ────────────── NEW PARKS & ATTRACTIONS ──────────────
  {
    id: 'telankhedi-garden',
    name: 'Telankhedi Garden',
    category: 'park',
    description: 'A historic royal garden built by the Bhonsle kings beside Telankhedi Lake. Features lush lawns, a Shiva temple (Kalyaneshwar Mandir), and a popular jogging track. One of Nagpur\'s oldest and most beloved gardens.',
    lat: 21.1361, lng: 79.0556,
    address: 'Bharat Nagar, Telankhedi Lake Road, Nagpur',
    area: 'Bharat Nagar',
    images: [
      WM('Telankhedi_Garden_Nagpur_-_Mapillary_(NC98dLGUSz8ghhvmDEEN_Q).jpg'),
      WM('Telangkhedi_Garden.jpg'),
      WM('Kalyaneshwar_Mandir_Telankhedi_Nagpur.jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — CC-BY-SA contributors (Mapillary, Wiki Loves Monuments)',
    source: 'OpenStreetMap / NMC',
    sourceUrl: 'https://en.wikipedia.org/wiki/Telankhedi_Garden',
    lastUpdated: '2025-03-05',
    hours: '6:00 AM – 9:00 AM, 4:00 PM – 8:00 PM',
    entryFee: 'Free',
    verified: true,
    tags: ['Garden', 'Lake', 'Jogging', 'Temple', 'Royal', 'Historic'],
    historicalContext: 'Built by the Bhonsle royal family alongside Telankhedi Lake, this garden and the Kalyaneshwar Mandir have been local landmarks for over two centuries.',
    nearbyIds: ['futala-lake', 'ambazari-lake'],
  },
  {
    id: 'kasturchand-park',
    name: 'Kasturchand Park',
    category: 'landmark',
    description: 'A historic public ground in the heart of Nagpur, donated by Shree Kasturchand Daga. The venue for major public events, rallies, exhibitions, and the annual Nagpur Mahotsav. Features a statue of Kasturchand Daga.',
    lat: 21.1494, lng: 79.0872,
    address: 'Kasturchand Park, Central Nagpur',
    area: 'Sitabuldi',
    images: [
      WM('Kasturchandparknagpur.jpg'),
      WM('Statue_of_Kasturchand_Daga,_Nagpur_-_panoramio.jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — CC-BY-SA (Ganesh Dhamodkar)',
    source: 'OpenStreetMap / NMC',
    sourceUrl: 'https://en.wikipedia.org/wiki/Kasturchand_Park',
    lastUpdated: '2025-02-25',
    hours: 'Open 24 hours (public ground)',
    entryFee: 'Free',
    verified: true,
    tags: ['Park', 'Ground', 'Events', 'Historic', 'Central', 'Statue'],
    historicalContext: 'Donated by the late Shree Kasturchand Daga, this ground has witnessed countless historic rallies, political meetings, and cultural events throughout Nagpur\'s modern history.',
    nearbyIds: ['sitabuldi-fort', 'zero-mile'],
  },
  {
    id: 'gandhi-sagar',
    name: 'Gandhi Sagar Lake & Floating Garden',
    category: 'park',
    description: 'A serene urban lake with a floating garden — one of Nagpur\'s unique attractions. The lake features boating and a musical fountain. Currently undergoing beautification with a ₹11.67 crore Phase 2 project.',
    lat: 21.1228, lng: 79.0611,
    address: 'Opposite Raman Science Centre, Nagpur',
    area: 'Sadar',
    images: [
      WM('GandhisagarLake.jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — CC-BY-SA',
    source: 'OpenStreetMap / NMC',
    sourceUrl: 'https://en.wikipedia.org/wiki/Gandhi_Sagar_Lake',
    lastUpdated: '2025-03-10',
    hours: '6:00 AM – 8:00 PM',
    entryFee: 'Free entry, boating ₹30',
    verified: true,
    tags: ['Lake', 'Floating Garden', 'Boating', 'Fountain', 'Family'],
    nearbyIds: ['raman-science-centre', 'futala-lake'],
  },
  {
    id: 'japanese-garden',
    name: 'Japanese Garden',
    category: 'park',
    description: 'A tranquil Japanese-style garden in Seminary Hills, featuring manicured landscapes, a small pond, walking paths, and panoramic views of the city. A peaceful retreat popular with morning walkers.',
    lat: 21.1811, lng: 79.0467,
    address: 'Seminary Hills, Nagpur',
    area: 'Seminary Hills',
    images: [
      'https://images.pexels.com/photos/1108572/pexels-photo-1108572.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (Japanese-style garden, no specific Wikimedia photo available)',
    source: 'OpenStreetMap / NMC',
    lastUpdated: '2025-02-20',
    hours: '6:00 AM – 10:00 AM, 4:00 PM – 7:00 PM',
    entryFee: 'Free',
    verified: true,
    tags: ['Garden', 'Japanese', 'Hills', 'Walking', 'Peaceful', 'Views'],
    nearbyIds: ['deekshabhoomi', 'ambazari-lake'],
  },
  {
    id: 'gorewada-zoo',
    name: 'Gorewada International Zoo',
    category: 'attraction',
    description: 'A large wildlife park and zoo project on the northern outskirts of Nagpur, surrounding Gorewada Lake. Features a safari, biodiversity park, and rescue center. One of the largest zoo projects in India.',
    lat: 21.2167, lng: 79.0500,
    address: 'Gorewada, North Nagpur',
    area: 'Gorewada',
    images: [
      WM('Tiger_in_Wild_Gorewada_Zoo_Nagpur.jpg'),
    ],
    imageAttribution: 'Wikimedia Commons — CC-BY-SA',
    source: 'OpenStreetMap / Forest Dept',
    sourceUrl: 'https://en.wikipedia.org/wiki/Gorewada_Zoo',
    lastUpdated: '2025-03-02',
    hours: '9:00 AM – 5:00 PM (closed Tuesday)',
    entryFee: '₹50 adults, ₹25 children (safari extra)',
    verified: true,
    tags: ['Zoo', 'Safari', 'Wildlife', 'Lake', 'Family', 'Biodiversity'],
    nearbyIds: ['koradi-temple'],
  },

  // ────────────── ACCOMMODATION ──────────────
  {
    id: 'ravi-bhavan',
    name: 'Ravi Bhavan Heritage Stay',
    category: 'accommodation',
    description: 'A colonial-era heritage bungalow converted into a boutique guesthouse in the Civil Lines area. Offers quiet, character-filled rooms with traditional Maharashtrian breakfast.',
    lat: 21.1494, lng: 79.0789,
    address: 'Civil Lines, Nagpur',
    area: 'Civil Lines',
    images: [
      'https://images.pexels.com/photos/3912074/pexels-photo-3912074.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (heritage room)',
    source: 'OpenStreetMap',
    lastUpdated: '2025-02-15',
    hours: '24-hour check-in',
    priceLevel: 2,
    verified: false,
    tags: ['Heritage', 'Boutique', 'Colonial', 'Budget'],
    nearbyIds: ['deekshabhoomi', 'haldiram-nagpur', 'maharajbagh'],
  },
  {
    id: 'backpacker-hostel',
    name: 'Nagpur Backpacker Hostel',
    category: 'accommodation',
    description: 'A clean, affordable hostel popular with budget travelers exploring central India. Dormitory and private rooms, shared kitchen, and travel desk.',
    lat: 21.1522, lng: 79.0956,
    address: 'Dhantoli, Nagpur',
    area: 'Dhantoli',
    images: [
      'https://images.pexels.com/photos/4907190/pexels-photo-4907190.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (hostel dormitory)',
    source: 'OpenStreetMap',
    lastUpdated: '2025-02-10',
    hours: '24-hour check-in',
    priceLevel: 1,
    verified: false,
    tags: ['Hostel', 'Budget', 'Dormitory', 'Backpacker'],
    nearbyIds: ['haldiram-nagpur'],
  },

  // ────────────── RESTAURANTS ──────────────
  {
    id: 'haldiram-nagpur',
    name: 'Haldiram\'s Nagpur',
    category: 'restaurant',
    description: 'Iconic Nagpur institution known for authentic Maharashtrian and North Indian cuisine. Famous for its Saoji cuisine, a spicy Nagpuri specialty unique to the Vidarbha region.',
    lat: 21.1486, lng: 79.0922,
    address: 'Central Bazaar Road, IT Park, Nagpur',
    area: 'Civil Lines',
    images: [
      'https://images.pexels.com/photos/9316203/pexels-photo-9316203.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (restaurant interior)',
    source: 'OpenStreetMap',
    lastUpdated: '2025-03-10',
    hours: '11:00 AM – 11:00 PM daily',
    priceLevel: 2,
    verified: true,
    foodTypes: ['restaurant', 'vegetarian', 'saoji'],
    tags: ['Saoji', 'Maharashtrian', 'Vegetarian', 'Family'],
    nearbyIds: ['zero-mile', 'sitabuldi-fort'],
  },
  {
    id: 'vishnuji-ki-rasoi',
    name: 'Vishnuji Ki Rasoi',
    category: 'restaurant',
    description: 'A popular restaurant chain specializing in authentic Nagpuri and Maharashtrian home-style cooking. Known for its thali meals, tarri poha, and traditional Vidarbha dishes.',
    lat: 21.1467, lng: 79.0856,
    address: 'Sitabuldi Main Road, Nagpur',
    area: 'Sitabuldi',
    images: [
      'https://images.pexels.com/photos/9316203/pexels-photo-9316203.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (restaurant interior)',
    source: 'OpenStreetMap',
    lastUpdated: '2025-03-08',
    hours: '8:00 AM – 11:00 PM daily',
    priceLevel: 1,
    verified: true,
    foodTypes: ['restaurant', 'vegetarian', 'breakfast', 'budget'],
    tags: ['Maharashtrian', 'Thali', 'Poha', 'Vegetarian', 'Vidarbha'],
    nearbyIds: ['sitabuldi-fort', 'kasturchand-park'],
  },
  {
    id: 'uttar-dakshin',
    name: 'Uttar Dakshin by Naivedhyam',
    category: 'restaurant',
    description: 'A multi-cuisine restaurant serving North Indian, South Indian, and Maharashtrian dishes. Popular for its dosa varieties, thalis, and family-friendly atmosphere.',
    lat: 21.1444, lng: 79.0833,
    address: 'Central Bazaar Road, Civil Lines, Nagpur',
    area: 'Civil Lines',
    images: [
      'https://images.pexels.com/photos/9589235/pexels-photo-9589235.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (South Indian food)',
    source: 'OpenStreetMap',
    lastUpdated: '2025-02-28',
    hours: '8:00 AM – 11:00 PM daily',
    priceLevel: 2,
    verified: true,
    foodTypes: ['restaurant', 'vegetarian'],
    tags: ['South Indian', 'North Indian', 'Dosa', 'Vegetarian', 'Family'],
    nearbyIds: ['haldiram-nagpur', 'zero-mile'],
  },
  {
    id: 'bellavista-cafe',
    name: 'BellaVista Cafe & Skybar',
    category: 'restaurant',
    description: 'A rooftop cafe and skybar with panoramic city views, continental cuisine, and a relaxed evening atmosphere. Popular with young professionals and couples.',
    lat: 21.1511, lng: 79.0889,
    address: 'Ramdaspeth, Nagpur',
    area: 'Ramdaspeth',
    images: [
      'https://images.pexels.com/photos/262047/pexels-photo-262047.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (rooftop cafe)',
    source: 'OpenStreetMap',
    lastUpdated: '2025-03-06',
    hours: '12:00 PM – 1:00 AM',
    priceLevel: 3,
    verified: true,
    foodTypes: ['cafe', 'restaurant'],
    tags: ['Rooftop', 'Continental', 'Skybar', 'Evening', 'Views'],
    nearbyIds: ['haldiram-nagpur', 'kasturchand-park'],
  },
  {
    id: 'huboho-cafe',
    name: 'Huboho Cafe & Eatery',
    category: 'restaurant',
    description: 'A trendy cafe known for specialty coffee, all-day breakfast, and fusion dishes. A favorite among Nagpur\'s cafe-hopping crowd with a cozy, modern interior.',
    lat: 21.1478, lng: 79.0911,
    address: 'Central Bazaar Road, Nagpur',
    area: 'Civil Lines',
    images: [
      'https://images.pexels.com/photos/1855214/pexels-photo-1855214.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (cafe interior)',
    source: 'OpenStreetMap',
    lastUpdated: '2025-03-04',
    hours: '9:00 AM – 11:00 PM',
    priceLevel: 2,
    verified: true,
    foodTypes: ['cafe', 'breakfast', 'vegetarian'],
    tags: ['Coffee', 'Breakfast', 'Cafe', 'Fusion', 'Trendy'],
    nearbyIds: ['haldiram-nagpur', 'bellavista-cafe'],
  },
  {
    id: 'bouffage-cafe',
    name: 'Bouffage Cafe and Bistro',
    category: 'restaurant',
    description: 'A chic bistro offering continental and Italian cuisine with a focus on fresh, locally-sourced ingredients. Known for its pasta, wood-fired pizzas, and desserts.',
    lat: 21.1489, lng: 79.0900,
    address: 'Ramdaspeth, Nagpur',
    area: 'Ramdaspeth',
    images: [
      'https://images.pexels.com/photos/2608033/pexels-photo-2608033.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (bistro food)',
    source: 'OpenStreetMap',
    lastUpdated: '2025-03-03',
    hours: '11:00 AM – 11:00 PM',
    priceLevel: 2,
    verified: true,
    foodTypes: ['cafe', 'restaurant'],
    tags: ['Italian', 'Continental', 'Pizza', 'Bistro', 'Pasta'],
    nearbyIds: ['huboho-cafe', 'bellavista-cafe'],
  },
  {
    id: 'seven-o-eleven',
    name: 'Seven O\' Eleven Cafe & Bistro',
    category: 'restaurant',
    description: 'A casual cafe-bistro serving multi-cuisine fare — from Indian curries to continental grills. Popular for group dining and casual hangouts.',
    lat: 21.1500, lng: 79.0878,
    address: 'Ramdaspeth, Nagpur',
    area: 'Ramdaspeth',
    images: [
      'https://images.pexels.com/photos/1307698/pexels-photo-1307698.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (bistro interior)',
    source: 'OpenStreetMap',
    lastUpdated: '2025-02-26',
    hours: '11:00 AM – 12:00 AM',
    priceLevel: 2,
    verified: true,
    foodTypes: ['cafe', 'restaurant'],
    tags: ['Multi-cuisine', 'Grill', 'Curry', 'Casual', 'Groups'],
    nearbyIds: ['bellavista-cafe', 'huboho-cafe'],
  },

  // ────────────── FOOD NEIGHBORHOODS & STREET FOOD ──────────────
  {
    id: 'saoji-street',
    name: 'Saoji Street Food Alley (Itwari)',
    category: 'food',
    description: 'A hidden cluster of street food stalls in Itwari serving authentic Nagpuri Saoji cuisine — intensely spiced mutton and chicken dishes unique to the Vidarbha region.',
    lat: 21.1589, lng: 79.1011,
    address: 'Itwari Road, Nagpur',
    area: 'Itwari',
    images: [
      'https://images.pexels.com/photos/984534/pexels-photo-984534.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/4570082/pexels-photo-4570082.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (Indian street food)',
    source: 'Local Discovery / OSM',
    lastUpdated: '2025-03-05',
    hours: '5:00 PM – 1:00 AM',
    priceLevel: 1,
    verified: false,
    foodTypes: ['street-food', 'saoji', 'budget'],
    tags: ['Street Food', 'Saoji', 'Non-Veg', 'Hidden Gem', 'Local'],
    nearbyIds: ['haldiram-nagpur'],
  },
  {
    id: 'sadar-street-food',
    name: 'Sadar Bazaar Street Food',
    category: 'food',
    description: 'Sadar is Nagpur\'s premier evening food street — chaat, pani puri, tarri poha, Nagpuri samosas, and kulfi line the bustling lanes. A must-visit for street food lovers.',
    lat: 21.1533, lng: 79.0778,
    address: 'Sadar Bazaar Road, Nagpur',
    area: 'Sadar',
    images: [
      'https://images.pexels.com/photos/4570082/pexels-photo-4570082.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/984534/pexels-photo-984534.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (Indian street food)',
    source: 'Local Discovery / OSM',
    lastUpdated: '2025-03-07',
    hours: '5:00 PM – 12:00 AM',
    priceLevel: 1,
    verified: false,
    foodTypes: ['street-food', 'breakfast', 'budget', 'vegetarian'],
    tags: ['Street Food', 'Chaat', 'Poha', 'Samosa', 'Kulfi', 'Evening'],
    nearbyIds: ['deekshabhoomi', 'futala-lake'],
  },
  {
    id: 'mominpura-street-food',
    name: 'Mominpura Food Street',
    category: 'food',
    description: 'Mominpura is legendary for its non-vegetarian street food — biryani, kebabs, nalli nihari, and sweet phirni. The best time to visit is during Ramadan for the iftar food bazaar.',
    lat: 21.1611, lng: 79.0944,
    address: 'Mominpura, Nagpur',
    area: 'Mominpura',
    images: [
      'https://images.pexels.com/photos/9316203/pexels-photo-9316203.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/984534/pexels-photo-984534.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (Indian street food)',
    source: 'Local Discovery / OSM',
    lastUpdated: '2025-03-06',
    hours: '6:00 PM – 2:00 AM',
    priceLevel: 1,
    verified: false,
    foodTypes: ['street-food', 'budget'],
    tags: ['Biryani', 'Kebab', 'Non-Veg', 'Ramadan', 'Iftar', 'Nihari'],
    nearbyIds: ['saoji-street'],
  },
  {
    id: 'tarri-poha-spots',
    name: 'Tarri Poha — Nagpur Breakfast Trail',
    category: 'food',
    description: 'Tarri poha is Nagpur\'s signature breakfast — flattened rice with a spicy tari (curry gravy). Multiple legendary stalls across the city serve their own versions. This entry covers the best-known poha clusters in Dhantoli, Civil Lines, and Sitabuldi.',
    lat: 21.1489, lng: 79.0889,
    address: 'Multiple locations — Dhantoli, Civil Lines, Sitabuldi',
    area: 'Central Nagpur',
    images: [
      'https://images.pexels.com/photos/4907190/pexels-photo-4907190.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (Indian breakfast food)',
    source: 'Local Discovery / OSM',
    lastUpdated: '2025-03-09',
    hours: '6:00 AM – 11:00 AM (breakfast hours)',
    priceLevel: 1,
    verified: false,
    foodTypes: ['breakfast', 'street-food', 'budget', 'vegetarian'],
    tags: ['Poha', 'Tarri', 'Breakfast', 'Signature Dish', 'Morning', 'Vegetarian'],
    nearbyIds: ['vishnuji-ki-rasoi', 'sadar-street-food'],
  },
  {
    id: 'tarodi-orange',
    name: 'Tarodi Orange Farm',
    category: 'food',
    description: 'A local orange orchard offering fresh Nagpur oranges — the fruit that gave Nagpur its nickname "Orange City." Seasonal visits available during winter harvest.',
    lat: 21.0989, lng: 79.0633,
    address: 'Tarodi, Nagpur outskirts',
    area: 'Tarodi',
    images: [
      'https://images.pexels.com/photos/984533/pexels-photo-984533.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    imageAttribution: 'Representative image — Pexels (Indian market scene)',
    source: 'Local Discovery / OSM',
    lastUpdated: '2025-01-20',
    hours: 'Seasonal: Oct–Feb, 9:00 AM – 5:00 PM',
    priceLevel: 1,
    verified: false,
    tags: ['Oranges', 'Orchard', 'Seasonal', 'Orange City'],
    nearbyIds: ['ambazari-lake'],
  },
];

export const SAFETY_REPORTS: SafetyReport[] = [
  {
    id: 'r1',
    placeId: 'ambazari-lake',
    placeName: 'Ambazari Lake Garden',
    area: 'Ambazari',
    category: 'infrastructure',
    status: 'pending',
    description: 'Broken railing near the boating area on the eastern side of the lake.',
    lat: 21.1392, lng: 79.0503,
    reportedAt: '2025-03-12',
    source: 'Citizen Report',
    evidenceCount: 2,
  },
  {
    id: 'r2',
    placeId: 'saoji-street',
    placeName: 'Saoji Street Food Alley',
    area: 'Itwari',
    category: 'sanitation',
    status: 'verified',
    description: 'Waterlogging reported in the alley during monsoon. NMC has initiated drainage work.',
    lat: 21.1591, lng: 79.1015,
    reportedAt: '2025-02-28',
    source: 'NMC Public Works',
    evidenceCount: 4,
  },
  {
    id: 'r3',
    placeId: 'sitabuldi-fort',
    placeName: 'Sitabuldi Fort',
    area: 'Sitabuldi',
    category: 'safety',
    status: 'unknown',
    description: 'Steep steps without handrails on the eastern approach. Caution advised for elderly visitors.',
    lat: 21.1456, lng: 79.0885,
    reportedAt: '2025-01-30',
    source: 'Citizen Report',
    evidenceCount: 1,
  },
  {
    id: 'r4',
    placeId: 'futala-lake',
    placeName: 'Futala Lake',
    area: 'Sadar',
    category: 'environment',
    status: 'pending',
    description: 'Accumulation of plastic waste along the northern promenade, especially on weekends.',
    lat: 21.1208, lng: 79.0571,
    reportedAt: '2025-03-14',
    source: 'Citizen Report',
    evidenceCount: 3,
  },
  {
    id: 'r5',
    placeId: 'zero-mile',
    placeName: 'Zero Mile Stone',
    area: 'Sitabuldi',
    category: 'infrastructure',
    status: 'rejected',
    description: 'Report of encroachment near the monument was investigated and found to be a temporary vendor stall, now cleared.',
    lat: 21.1497, lng: 79.0808,
    reportedAt: '2025-02-15',
    source: 'NMC Enforcement',
    evidenceCount: 1,
  },
  {
    id: 'r6',
    placeId: 'maharajbagh',
    placeName: 'Maharajbagh Zoo',
    area: 'Civil Lines',
    category: 'safety',
    status: 'verified',
    description: 'Adequate safety signage and barriers have been installed near animal enclosures following a citizen report.',
    lat: 21.1396, lng: 79.0658,
    reportedAt: '2025-02-05',
    source: 'PDKV Administration',
    evidenceCount: 5,
  },
];

// Weather fetched live from Open-Meteo (no API key required)
export const WEATHER_FALLBACK: WeatherData = {
  temperature: 0,
  condition: 'Loading…',
  humidity: 0,
  windSpeed: 0,
  retrievedAt: '',
  source: 'Open-Meteo (loading…)',
};

export async function fetchWeather(): Promise<WeatherData> {
  try {
    const url = 'https://api.open-meteo.com/v1/forecast?latitude=21.1458&longitude=79.0882&current=temperature_2m,relative_humidity_2m,wind_speed_10m,weather_code';
    const res = await fetch(url);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const data = await res.json();
    const code = data.current?.weather_code ?? 0;
    return {
      temperature: Math.round(data.current?.temperature_2m ?? 0),
      condition: weatherCodeToText(code),
      humidity: Math.round(data.current?.relative_humidity_2m ?? 0),
      windSpeed: Math.round(data.current?.wind_speed_10m ?? 0),
      retrievedAt: new Date().toISOString(),
      source: 'Open-Meteo (live)',
    };
  } catch {
    return {
      temperature: 0,
      condition: 'Unavailable',
      humidity: 0,
      windSpeed: 0,
      retrievedAt: '',
      source: 'Open-Meteo (fetch failed)',
    };
  }
}

function weatherCodeToText(code: number): string {
  if (code === 0) return 'Clear sky';
  if (code <= 2) return 'Partly cloudy';
  if (code === 3) return 'Overcast';
  if (code <= 48) return 'Foggy';
  if (code <= 57) return 'Drizzle';
  if (code <= 67) return 'Rain';
  if (code <= 77) return 'Snow';
  if (code <= 82) return 'Rain showers';
  if (code <= 86) return 'Snow showers';
  if (code <= 99) return 'Thunderstorm';
  return 'Unknown';
}

export function getPlaceById(id: string): Place | undefined {
  return PLACES.find(p => p.id === id);
}

export function getNearbyPlaces(place: Place): Place[] {
  return (place.nearbyIds || []).map(getPlaceById).filter(Boolean) as Place[];
}
